### ISSUE TITLE
Should the size be same in `allocate` and `deallocate`

### ISSUE THREAD

**Issue by hbsun2113** [mcgov/asan_alignment_example#1]
I notice you use `sizeof` in `allocate`, but use `alignof` in `deallocate`. Could you please tell me the reason? I think both of them should use `sizeof`. 
![image](https://user-images.githubusercontent.com/27994442/151521843-be142a09-56c3-48d9-88c7-911b3893e7bc.png)

Thanks!

**Comment by hbsun2113** [comment]
@mcgov

**Comment by mcgov** [comment]
Apologies for missing this issue until now and thank you for pointing it out!

This is definitely a situation where a comment would have been warranted to explain the discrepancy. I'm on a Linux machine at the moment but will take a look in a debugger tomorrow and give a full response with either an explanation or a correction.

**Comment by mcgov** [comment]
From reviewing my notes and digging through the debugger a bit, I think I can recall the general rationale for using alignof. I messed around a bit to try and reproduce the issue that it's use would prevent and couldn't reproduce it, so I think you're right that it's not needed and sizeof on both is the correct solution.

The general gist was that attempting to end one region and start another within any aligned qword will result in mangled metadata. However, in this example we used aligned_malloc to allocate the arena region and pad the size to align the 'cursor' to the next boundary. The poisoning procedure will handle that situation without issues. Even when you pass a size that is not qword aligned to unpoison, it unpoisons the end up to the qword boundary.

I suspect that so long as you align the start of a region to qword and pad the end to terminate on that same alignment, sizeof should be fine. I am glad you pointed this out, it's confusing and even if alignof were needed I should have commented it to explain why. I'll change this example up to use sizeof consistently and also use a type for the allocated item that isn't size_t, since it's not a great example of the alignment issue in the first place.

**Comment by mcgov** [comment]
Example is updated, thank you for the feedback and please reach back out if you have questions or notice any other issues!

**Comment by hbsun2113** [comment]
Thanks for your fix! Still have some questions about your code, and I comment inline, could you please take a look?
https://github.com/mcgov/asan_alignment_example/commit/55c3a2fc40cd88f2377bc88d5ac75c3d28c6c720#comments
![image](https://user-images.githubusercontent.com/27994442/165460409-12342dc9-cc88-4945-8ebf-8282ac748133.png)
