### ISSUE TITLE
Some questions for your change and code

### ISSUE THREAD

**Issue by hbsun2113** [mcgov/asan_alignment_example#2]
Thanks for your fix! Still have some questions about your code, and I comment inline, could you please take a look?
As you close the previous issue, so I have to create a new one.
https://github.com/mcgov/asan_alignment_example/commit/55c3a2fc40cd88f2377bc88d5ac75c3d28c6c720#comments
![image](https://user-images.githubusercontent.com/27994442/165460409-12342dc9-cc88-4945-8ebf-8282ac748133.png)

**Comment by mcgov** [comment]
Before we start: I wish you had been there from the start for code review! I got a lot of comments that still ultimately missed these things so very happy to have your eye on this.

The alignment does only need to be 8 byte aligned, however this alignment is only to account for the extra bytes in the allocation to ensure we don't have two allocations within the same byte of the shadow memory.
Consider the example of a dword at address 0. The allocation only takes up 4 bytes of the 8, so the shadow memory value will by 0x04.
0 1 2 3 4 5 6 7  
a a a a  x x x x   -> shadow byte 0x04

The compiler and runtime handle this alignment requirement transparently when they allocate, since we're laying things out ourselves we have to enforce it. If we were to cram two dwords in that qword region, there would be no way to represent the boundary between them. ASans manual poisoning function would see this and assume the region is contiguous. The resulting shadow byte would be 0x00.
0 1 2 3 4 5 6 7  
a a a a b b b b

Worse, if these were poisoned separately, the runtime doesn't have a way to poison only the 4 trailing bytes. If you were to attempt to allocate a, then b, then deallocate and poison b, it would either poison the entire region or not poison b. I can't remember offhand which occurs but these examples should be laid out `bad_unpoison` -> `unpoison.exe`.

So: separate from that alignment requirement we still add poisoned padding to the region. the padding in between each block of elements determines how large of a bad offset ASan will be able to detect. If an overflow reaches beyond the poisoned region into an unpoisoned region then a report will not be generated. You should use at least the size of an individual element in the block as padding, since overflows will often occur close to the boundaries due to off-by-one indexing errors. Larger padding in between allocations gives you a better chance of catching larger offsets outside of the allocation. This could help catch additional bugs if the overflow is due to bad pointer math instead of a simple off-by-one error.

That should be made clear and documented in the example, as well as in the actual documentation we published. I'll raise a PR for both and make sure it's explicit. The only reason for using two bytes instead of one in the example was to make the padding stand out more when the shadow bytes were printed. I will modify the example to detail exactly why more padding might be beneficial.

**Comment by hbsun2113** [comment]
Thanks for your explanation!! I don't know [addressSanitizer](https://docs.microsoft.com/en-us/cpp/sanitizers/asan-shadow-bytes?view=msvc-170)/memoryAllocation very well so want to ask more:
1. Under what circumstances would you "cram two dwords in that qword region"?  
2. You use two bytes to make padding here, how many bytes are Asan using to make padding by default(e.g. don't use the custom allocator)
3. Could you please share the link to the PR and the actual documentation?
4. All the above discussions are based on 1dword==8byte. But according to [Microsoft](https://docs.microsoft.com/en-us/cpp/assembler/masm/dword?view=msvc-170#:~:text=a%20double%20word%20(-,4%20bytes,-)%20of%20storage%20for), 1dword==4byte. Is there anything I missed?

**Comment by hbsun2113** [comment]
kindly ping @mcgov

**Comment by mcgov** [comment]
> Thanks for your explanation!! I don't know [addressSanitizer](https://docs.microsoft.com/en-us/cpp/sanitizers/asan-shadow-bytes?view=msvc-170)/memoryAllocation very well so want to ask more:
> 
> 1. Under what circumstances would you "cram two dwords in that qword region"?

Just trying to illustrate that if objects 1) aren't aligned and 2) have padding between them then there is no way to detect an overflow from one object into the other.

> 2. You use two bytes to make padding here, how many bytes are Asan using to make padding by default(e.g. don't use the custom allocator)

see `max_redzone` and `redzone` runtime options at https://github.com/google/sanitizers/wiki/AddressSanitizerFlags
The VS asan runtime is almost exactly the same as the regular clang one. At some point (possibly now) they should be the same runtime. I've moved teams so not sure of the current status.

> 3. Could you please share the link to the PR and the actual documentation?

There's Kostya's paper describing the algorithm: [AddressSanitizer](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/37752.pdf)
Microsoft, LLVM, and Google all have official documentation relating to ASan you can search for, my limit for copy/pasting links is 1.

> 4. All the above discussions are based on 1dword==8byte. But according to [Microsoft](https://docs.microsoft.com/en-us/cpp/assembler/masm/dword?view=msvc-170#:~:text=a%20double%20word%20(-,4%20bytes,-)%20of%20storage%20for), 1dword==4byte. Is there anything I missed?

A dword is not 8 bytes. ASan maps 8 bytes aka `qword` or `uint64_t` and `int64_t` to 8 bits of shadow memory.
[Sanitizers/Shadow Bytes](https://docs.microsoft.com/en-us/cpp/sanitizers/asan-shadow-bytes?view=msvc-170)

**Comment by mcgov** [comment]
Going to close, feel free to follow up if you have more questions!
